package net.calba.backpain.dao.mybatis;

import java.util.List;

import net.calba.backpain.model.ClientType;
import net.calba.backpain.model.ClientTypeExample;

import org.apache.ibatis.annotations.Param;

public interface ClientTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int countByExample(ClientTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByExample(ClientTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByPrimaryKey(Integer clientTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insert(ClientType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insertSelective(ClientType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    List<ClientType> selectByExample(ClientTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    ClientType selectByPrimaryKey(Integer clientTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExampleSelective(@Param("record") ClientType record, @Param("example") ClientTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExample(@Param("record") ClientType record, @Param("example") ClientTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKeySelective(ClientType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKey(ClientType record);
}