package net.calba.backpain.dao.mybatis;

import java.util.List;

import net.calba.backpain.model.FormQuestionClient;
import net.calba.backpain.model.FormQuestionClientExample;
import net.calba.backpain.model.MoniterSystem;

import org.apache.ibatis.annotations.Param;

public interface FormQuestionClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int countByExample(FormQuestionClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int deleteByExample(FormQuestionClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int deleteByPrimaryKey(Integer formQuestionClientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int insert(FormQuestionClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int insertSelective(FormQuestionClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    List<FormQuestionClient> selectByExample(FormQuestionClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    FormQuestionClient selectByPrimaryKey(Integer formQuestionClientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int updateByExampleSelective(@Param("record") FormQuestionClient record, @Param("example") FormQuestionClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int updateByExample(@Param("record") FormQuestionClient record, @Param("example") FormQuestionClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int updateByPrimaryKeySelective(FormQuestionClient record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    int updateByPrimaryKey(FormQuestionClient record);

	void insertMoniterSystem(FormQuestionClient quest);
}