package net.calba.backpain.dao.mybatis;

import java.util.List;

import net.calba.backpain.model.HeightUnits;
import net.calba.backpain.model.HeightUnitsExample;

import org.apache.ibatis.annotations.Param;

public interface HeightUnitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int countByExample(HeightUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByExample(HeightUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByPrimaryKey(Integer heightUnitsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insert(HeightUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insertSelective(HeightUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    List<HeightUnits> selectByExample(HeightUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    HeightUnits selectByPrimaryKey(Integer heightUnitsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExampleSelective(@Param("record") HeightUnits record, @Param("example") HeightUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExample(@Param("record") HeightUnits record, @Param("example") HeightUnitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKeySelective(HeightUnits record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table heightunits
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKey(HeightUnits record);
}