package net.calba.backpain.dao.mybatis;

import java.util.List;

import net.calba.backpain.model.PersonalDetails;
import net.calba.backpain.model.PersonalDetailsExample;

import org.apache.ibatis.annotations.Param;

public interface PersonalDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int countByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByPrimaryKey(Integer personalDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insert(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insertSelective(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    List<PersonalDetails> selectByExample(PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    PersonalDetails selectByPrimaryKey(Integer personalDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExampleSelective(@Param("record") PersonalDetails record, @Param("example") PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExample(@Param("record") PersonalDetails record, @Param("example") PersonalDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKeySelective(PersonalDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKey(PersonalDetails record);
}