package net.calba.backpain.dao.mybatis;

import java.util.List;
import java.util.Map;

import net.calba.backpain.model.HNPTable;
import net.calba.backpain.model.QuestionAnswer;
import net.calba.backpain.model.QuestionAnswerExample;
import org.apache.ibatis.annotations.Param;

public interface QuestionAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int countByExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int deleteByExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int insert(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int insertSelective(QuestionAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    List<QuestionAnswer> selectByExample(QuestionAnswerExample example);
    
   
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    List<QuestionAnswer> selectExample(QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int updateByExampleSelective(@Param("record") QuestionAnswer record, @Param("example") QuestionAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    int updateByExample(@Param("record") QuestionAnswer record, @Param("example") QuestionAnswerExample example);
    
    /**
     * 
     * @return
     */
    int updateNullValues();
    
    /**
     * 
     * @param record
     * @param example
     * @return
     */
    int updateByOptionId(@Param("record") QuestionAnswer record, @Param("example") QuestionAnswerExample example);
    /**
     * 
     * @return
     */
    List getHnpTableValue();
    /**
     * 
     * @return
     */
    List getHnpHistoryTableValue();
    /**
     * 
     * @return
     */
    List getHnpHistoryPastValue();
    /**
     * 
     * @return
     */
    List getHnpHistory1to2Value();

    /**
     * 
     * @return
     */
	List getHnpHistory3to5Value();

	/**
	 * 
	 * @return
	 */
	List getHnpHistory5Value();

	/**
	 * 
	 * @param records
	 */
	void insertmasterAnswerTable(QuestionAnswer records);

	



}