package net.calba.backpain.dao.mybatis;

import java.util.List;
import java.util.Map;

import net.calba.backpain.model.Question;
import net.calba.backpain.model.QuestionExample;
import org.apache.ibatis.annotations.Param;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    Question selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int updateByExampleSelective(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int updateByExample(@Param("record") Question record, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.question
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    int updateByPrimaryKey(Question record);
    
    /**
     * 
     * @param parameters Map<String, Integer> 
     * @return List<Question> 
     */
    List<Question> selectQuestionListing(Map<String, Integer> parameters);
}