package net.calba.backpain.dao.mybatis;

import java.util.List;
import net.calba.backpain.model.Report;
import net.calba.backpain.model.ReportExample;
import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int countByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int deleteByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int deleteByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int insertSelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    List<Report> selectByExample(ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    Report selectByPrimaryKey(Long reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int updateByExampleSelective(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int updateByExample(@Param("record") Report record, @Param("example") ReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int updateByPrimaryKeySelective(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.report
     *
     * @mbggenerated Sun Nov 10 11:06:52 PKT 2013
     */
    int updateByPrimaryKey(Report record);
}