package net.calba.backpain.dao.mybatis;

import java.util.List;

import net.calba.backpain.model.Telephone;
import net.calba.backpain.model.TelephoneExample;

import org.apache.ibatis.annotations.Param;

public interface TelephoneMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int countByExample(TelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByExample(TelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int deleteByPrimaryKey(Integer telephoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insert(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int insertSelective(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    List<Telephone> selectByExample(TelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    Telephone selectByPrimaryKey(Integer telephoneId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExampleSelective(@Param("record") Telephone record, @Param("example") TelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByExample(@Param("record") Telephone record, @Param("example") TelephoneExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKeySelective(Telephone record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table telephone
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    int updateByPrimaryKey(Telephone record);
}