package net.calba.backpain.model;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.addressid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.line1
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String line1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.line2
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String line2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.line3
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String line3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.country
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.postcode
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.addressid
     *
     * @return the value of address.addressid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.addressid
     *
     * @param addressId the value for address.addressid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.line1
     *
     * @return the value of address.line1
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getLine1() {
        return line1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.line1
     *
     * @param line1 the value for address.line1
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setLine1(String line1) {
        this.line1 = line1 == null ? null : line1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.line2
     *
     * @return the value of address.line2
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getLine2() {
        return line2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.line2
     *
     * @param line2 the value for address.line2
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setLine2(String line2) {
        this.line2 = line2 == null ? null : line2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.line3
     *
     * @return the value of address.line3
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getLine3() {
        return line3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.line3
     *
     * @param line3 the value for address.line3
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setLine3(String line3) {
        this.line3 = line3 == null ? null : line3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.country
     *
     * @return the value of address.country
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.country
     *
     * @param country the value for address.country
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.postcode
     *
     * @return the value of address.postcode
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.postcode
     *
     * @param postcode the value for address.postcode
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.clinetid
     *
     * @return the value of address.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.clinetid
     *
     * @param clientId the value for address.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }
}