package net.calba.backpain.model;

public class ClientType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clienttype.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clienttype.clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String clientType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clienttype.clienttypeid
     *
     * @return the value of clienttype.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientTypeId() {
        return clientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clienttype.clienttypeid
     *
     * @param clientTypeId the value for clienttype.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientTypeId(Integer clientTypeId) {
        this.clientTypeId = clientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clienttype.clienttype
     *
     * @return the value of clienttype.clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clienttype.clienttype
     *
     * @param clientType the value for clienttype.clienttype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientType(String clientType) {
        this.clientType = clientType == null ? null : clientType.trim();
    }
}