package net.calba.backpain.model;

public class ClientState {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientstate.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientstate.clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String clientState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientstate.clientstateid
     *
     * @return the value of clientstate.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientStateId() {
        return clientStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientstate.clientstateid
     *
     * @param clientStateId the value for clientstate.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientStateId(Integer clientStateId) {
        this.clientStateId = clientStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientstate.clientstate
     *
     * @return the value of clientstate.clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getClientState() {
        return clientState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientstate.clientstate
     *
     * @param clientState the value for clientstate.clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientState(String clientState) {
        this.clientState = clientState == null ? null : clientState.trim();
    }
}