package net.calba.backpain.model;

import java.util.ArrayList;
import java.util.List;

public class ClientStateExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public ClientStateExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientStateIdIsNull() {
            addCriterion("clientstateid is null");
            return (Criteria) this;
        }

        public Criteria andClientStateIdIsNotNull() {
            addCriterion("clientstateid is not null");
            return (Criteria) this;
        }

        public Criteria andClientStateIdEqualTo(Integer value) {
            addCriterion("clientstateid =", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdNotEqualTo(Integer value) {
            addCriterion("clientstateid <>", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdGreaterThan(Integer value) {
            addCriterion("clientstateid >", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clientstateid >=", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdLessThan(Integer value) {
            addCriterion("clientstateid <", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdLessThanOrEqualTo(Integer value) {
            addCriterion("clientstateid <=", value, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdIn(List<Integer> values) {
            addCriterion("clientstateid in", values, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdNotIn(List<Integer> values) {
            addCriterion("clientstateid not in", values, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdBetween(Integer value1, Integer value2) {
            addCriterion("clientstateid between", value1, value2, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clientstateid not between", value1, value2, "clientStateId");
            return (Criteria) this;
        }

        public Criteria andClientStateIsNull() {
            addCriterion("clientstate is null");
            return (Criteria) this;
        }

        public Criteria andClientStateIsNotNull() {
            addCriterion("clientstate is not null");
            return (Criteria) this;
        }

        public Criteria andClientStateEqualTo(String value) {
            addCriterion("clientstate =", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateNotEqualTo(String value) {
            addCriterion("clientstate <>", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateGreaterThan(String value) {
            addCriterion("clientstate >", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateGreaterThanOrEqualTo(String value) {
            addCriterion("clientstate >=", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateLessThan(String value) {
            addCriterion("clientstate <", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateLessThanOrEqualTo(String value) {
            addCriterion("clientstate <=", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateLike(String value) {
            addCriterion("clientstate like", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateNotLike(String value) {
            addCriterion("clientstate not like", value, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateIn(List<String> values) {
            addCriterion("clientstate in", values, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateNotIn(List<String> values) {
            addCriterion("clientstate not in", values, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateBetween(String value1, String value2) {
            addCriterion("clientstate between", value1, value2, "clientState");
            return (Criteria) this;
        }

        public Criteria andClientStateNotBetween(String value1, String value2) {
            addCriterion("clientstate not between", value1, value2, "clientState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientstate
     *
     * @mbggenerated do_not_delete_during_merge Wed May 22 17:15:02 PKT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientstate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}