package net.calba.backpain.model;

import java.util.Date;

public class ClientForm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer clientFormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.state
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.startdate
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.lastupdated
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.clinetid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.clientform.formid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer formId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.clientformid
     *
     * @return the value of calba.clientform.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Integer getClientFormId() {
        return clientFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.clientformid
     *
     * @param clientFormId the value for calba.clientform.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setClientFormId(Integer clientFormId) {
        this.clientFormId = clientFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.state
     *
     * @return the value of calba.clientform.state
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.state
     *
     * @param state the value for calba.clientform.state
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.startdate
     *
     * @return the value of calba.clientform.startdate
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.startdate
     *
     * @param startDate the value for calba.clientform.startdate
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.lastupdated
     *
     * @return the value of calba.clientform.lastupdated
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.lastupdated
     *
     * @param lastUpdated the value for calba.clientform.lastupdated
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.clinetid
     *
     * @return the value of calba.clientform.clinetid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.clinetid
     *
     * @param clientId the value for calba.clientform.clinetid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.clientform.formid
     *
     * @return the value of calba.clientform.formid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.clientform.formid
     *
     * @param formId the value for calba.clientform.formid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }
}