package net.calba.backpain.model;

import java.util.Date;
import java.util.List;

public class Client {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientId;
    
    
    private Integer setForm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.forename
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String foreName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.surname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String surName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.dateofbirth
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Date dateOfBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.userid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String userId;
    private String sex;
    private String mobile;
    private String careComment;
    public String getComment1() {
		return comment1;
	}

	public void setComment1(String comment1) {
		this.comment1 = comment1;
	}

	public String getComment2() {
		return comment2;
	}

	public void setComment2(String comment2) {
		this.comment2 = comment2;
	}

	public String getComment3() {
		return comment3;
	}

	public void setComment3(String comment3) {
		this.comment3 = comment3;
	}

	public String getComment4() {
		return comment4;
	}

	public void setComment4(String comment4) {
		this.comment4 = comment4;
	}

	public String getComment5() {
		return comment5;
	}

	public void setComment5(String comment5) {
		this.comment5 = comment5;
	}

	private Integer assessmentformflag;
    private String comment1;
    private String comment2;
    private String comment3;
    private String comment4;
    private String comment5;

    public String getCareComment() {
		return careComment;
	}

	public void setCareComment(String careComment) {
		this.careComment = careComment;
	}

	public Integer getAssessmentformflag() {
		return assessmentformflag;
	}

	public void setAssessmentformflag(Integer assessmentformflag) {
		this.assessmentformflag = assessmentformflag;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.hashedpassword
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String hashedPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.roleid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.createddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.lastupdateddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Date lastUpdatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientStateId;
    /**
     * this field for  user password
     */
    private String password;
    
   

	private Role role;
    
    private ClientType clientType;
    
    private List<ClientForm> clientForms;
    private Integer DisabilityFormUpdate;
    
    
 
	/**
	 * 
	 */
	public Client() {		
	}

	/**
	 * @param clientId
	 */
	public Client(Integer clientId) {
		
		this.clientId = clientId;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public ClientType getClientType() {
		return clientType;
	}

	public void setClientType(ClientType clientType) {
		this.clientType = clientType;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clinetid
     *
     * @return the value of client.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clinetid
     *
     * @param clientId the value for client.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.forename
     *
     * @return the value of client.forename
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getForeName() {
        return foreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.forename
     *
     * @param foreName the value for client.forename
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setForeName(String foreName) {
        this.foreName = foreName == null ? null : foreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.surname
     *
     * @return the value of client.surname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getSurName() {
        return surName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.surname
     *
     * @param surName the value for client.surname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setSurName(String surName) {
        this.surName = surName == null ? null : surName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.dateofbirth
     *
     * @return the value of client.dateofbirth
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.dateofbirth
     *
     * @param dateOfBirth the value for client.dateofbirth
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.userid
     *
     * @return the value of client.userid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.userid
     *
     * @param userId the value for client.userid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.hashedpassword
     *
     * @return the value of client.hashedpassword
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getHashedPassword() {
        return hashedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.hashedpassword
     *
     * @param hashedPassword the value for client.hashedpassword
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword == null ? null : hashedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.roleid
     *
     * @return the value of client.roleid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.roleid
     *
     * @param roleId the value for client.roleid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.createddate
     *
     * @return the value of client.createddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.createddate
     *
     * @param createdDate the value for client.createddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.lastupdateddate
     *
     * @return the value of client.lastupdateddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.lastupdateddate
     *
     * @param lastUpdatedDate the value for client.lastupdateddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.projectid
     *
     * @return the value of client.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.projectid
     *
     * @param projectId the value for client.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clienttypeid
     *
     * @return the value of client.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientTypeId() {
        return clientTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clienttypeid
     *
     * @param clientTypeId the value for client.clienttypeid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientTypeId(Integer clientTypeId) {
        this.clientTypeId = clientTypeId;
    }

    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clientstateid
     *
     * @return the value of client.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientStateId() {
        return clientStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clientstateid
     *
     * @param clientStateId the value for client.clientstateid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientStateId(Integer clientStateId) {
        this.clientStateId = clientStateId;
    }    

	public List<ClientForm> getClientForms() {
		return clientForms;
	}

	public void setClientForms(List<ClientForm> clientForms) {
		this.clientForms = clientForms;
	}	
	

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
	

	public Integer getSetForm() {
		return setForm;
	}

	public void setSetForm(Integer setForm) {
		this.setForm = setForm;
	}
	 public Integer getDisabilityFormUpdate() {
			return DisabilityFormUpdate;
		}

		public void setDisabilityFormUpdate(Integer disabilityFormUpdate) {
			DisabilityFormUpdate = disabilityFormUpdate;
		}

		@Override
		public String toString() {
			return "Client [clientId=" + clientId + ", setForm=" + setForm
					+ ", foreName=" + foreName + ", surName=" + surName
					+ ", dateOfBirth=" + dateOfBirth + ", userId=" + userId
					+ ", sex=" + sex + ", mobile=" + mobile
					+ ", hashedPassword=" + hashedPassword + ", roleId="
					+ roleId + ", createdDate=" + createdDate
					+ ", lastUpdatedDate=" + lastUpdatedDate + ", projectId="
					+ projectId + ", clientTypeId=" + clientTypeId
					+ ", clientStateId=" + clientStateId + ", password="
					+ password + ", role=" + role + ", clientType="
					+ clientType + ", clientForms=" + clientForms
					+ ", DisabilityFormUpdate=" + DisabilityFormUpdate
					+ ", getRole()=" + getRole() + ", getClientType()="
					+ getClientType() + ", getClientId()=" + getClientId()
					+ ", getForeName()=" + getForeName() + ", getSurName()="
					+ getSurName() + ", getDateOfBirth()=" + getDateOfBirth()
					+ ", getUserId()=" + getUserId() + ", getHashedPassword()="
					+ getHashedPassword() + ", getRoleId()=" + getRoleId()
					+ ", getCreatedDate()=" + getCreatedDate()
					+ ", getLastUpdatedDate()=" + getLastUpdatedDate()
					+ ", getProjectId()=" + getProjectId()
					+ ", getClientTypeId()=" + getClientTypeId()
					+ ", getClientStateId()=" + getClientStateId()
					+ ", getClientForms()=" + getClientForms()
					+ ", getPassword()=" + getPassword() + ", getSetForm()="
					+ getSetForm() + ", getDisabilityFormUpdate()="
					+ getDisabilityFormUpdate() + ", getSex()=" + getSex()
					+ ", getMobile()=" + getMobile() + ", getClass()="
					+ getClass() + ", hashCode()=" + hashCode()
					+ ", toString()=" + super.toString() + "]";
		}

		public String getSex() {
			return sex;
		}

		public void setSex(String sex) {
			this.sex = sex;
		}

		public String getMobile() {
			return mobile;
		}

		public void setMobile(String mobile) {
			this.mobile = mobile;
		}

	

	
    
    
}