package net.calba.backpain.model;

public class FormQuestionClient {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.formquestionclient.formquestionclientid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer formQuestionClientId;
    private Integer moniterseqId;
    
    private Integer userId;
    
    private String score;
    
    private Integer setId;
	private String date;
	  

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.formquestionclient.value
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.formquestionclient.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer clientFormId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.formquestionclient.questionid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    private Integer questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.formquestionclient.formquestionclientid
     *
     * @return the value of calba.formquestionclient.formquestionclientid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    
    
    public Integer getFormQuestionClientId() {
        return formQuestionClientId;
    }

    public Integer getSetId() {
		return setId;
	}

	public void setSetId(Integer setId) {
		this.setId = setId;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}
	

	public Integer getMoniterseqId() {
		return moniterseqId;
	}

	public void setMoniterseqId(Integer moniterseqId) {
		this.moniterseqId = moniterseqId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.formquestionclient.formquestionclientid
     *
     * @param formQuestionClientId the value for calba.formquestionclient.formquestionclientid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setFormQuestionClientId(Integer formQuestionClientId) {
        this.formQuestionClientId = formQuestionClientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.formquestionclient.value
     *
     * @return the value of calba.formquestionclient.value
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.formquestionclient.value
     *
     * @param value the value for calba.formquestionclient.value
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.formquestionclient.clientformid
     *
     * @return the value of calba.formquestionclient.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Integer getClientFormId() {
        return clientFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.formquestionclient.clientformid
     *
     * @param clientFormId the value for calba.formquestionclient.clientformid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setClientFormId(Integer clientFormId) {
        this.clientFormId = clientFormId;
    }
    
    /**
     * 
     * @return
     */

 

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.formquestionclient.questionid
     *
     * @return the value of calba.formquestionclient.questionid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Integer getQuestionId() {
        return questionId;
    }

    public String getScore() {
		return score;
	}

	public void setScore(String score) {
		this.score = score;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.formquestionclient.questionid
     *
     * @param questionId the value for calba.formquestionclient.questionid
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

	@Override
	public String toString() {
		return "FormQuestionClient [formQuestionClientId="
				+ formQuestionClientId + ", moniterseqId=" + moniterseqId
				+ ", userId=" + userId + ", score=" + score + ", setId="
				+ setId + ", date=" + date + ", value=" + value
				+ ", clientFormId=" + clientFormId + ", questionId="
				+ questionId + ", getFormQuestionClientId()="
				+ getFormQuestionClientId() + ", getSetId()=" + getSetId()
				+ ", getUserId()=" + getUserId() + ", getDate()=" + getDate()
				+ ", getMoniterseqId()=" + getMoniterseqId() + ", getValue()="
				+ getValue() + ", getClientFormId()=" + getClientFormId()
				+ ", getQuestionId()=" + getQuestionId() + ", getScore()="
				+ getScore() + ", getClass()=" + getClass() + ", hashCode()="
				+ hashCode() + ", toString()=" + super.toString() + "]";
	}

	
	

	
    
    
}