package net.calba.backpain.model;

import java.util.List;

public class Form {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.formid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer formid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.formname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String formname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.formtype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String formtype;
    /**
     *  form questions.
     *
     */    
    private List<Question> questions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.formid
     *
     * @return the value of form.formid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getFormid() {
        return formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.formid
     *
     * @param formid the value for form.formid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setFormid(Integer formid) {
        this.formid = formid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.formname
     *
     * @return the value of form.formname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getFormname() {
        return formname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.formname
     *
     * @param formname the value for form.formname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setFormname(String formname) {
        this.formname = formname == null ? null : formname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.formtype
     *
     * @return the value of form.formtype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getFormtype() {
        return formtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.formtype
     *
     * @param formtype the value for form.formtype
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setFormtype(String formtype) {
        this.formtype = formtype == null ? null : formtype.trim();
    }

	public List<Question> getQuestions() {
		return questions;
	}

	public void setQuestions(List<Question> questions) {
		this.questions = questions;
	}

	@Override
	public String toString() {
		return "Form [formid=" + formid + ", formname=" + formname
				+ ", formtype=" + formtype + ", questions=" + questions + "]";
	}
    
	
	
    
}