package net.calba.backpain.model;

import java.util.ArrayList;
import java.util.List;

public class FormQuestionClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public FormQuestionClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andFormQuestionClientIdIsNull() {
            addCriterion("formquestionclientid is null");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdIsNotNull() {
            addCriterion("formquestionclientid is not null");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdEqualTo(Integer value) {
            addCriterion("formquestionclientid =", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdNotEqualTo(Integer value) {
            addCriterion("formquestionclientid <>", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdGreaterThan(Integer value) {
            addCriterion("formquestionclientid >", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("formquestionclientid >=", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdLessThan(Integer value) {
            addCriterion("formquestionclientid <", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("formquestionclientid <=", value, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdIn(List<Integer> values) {
            addCriterion("formquestionclientid in", values, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdNotIn(List<Integer> values) {
            addCriterion("formquestionclientid not in", values, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdBetween(Integer value1, Integer value2) {
            addCriterion("formquestionclientid between", value1, value2, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andFormQuestionClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("formquestionclientid not between", value1, value2, "formQuestionClientId");
            return (Criteria) this;
        }

        public Criteria andValueIsNull() {
            addCriterion("value is null");
            return (Criteria) this;
        }

        public Criteria andValueIsNotNull() {
            addCriterion("value is not null");
            return (Criteria) this;
        }

        public Criteria andValueEqualTo(String value) {
            addCriterion("value =", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotEqualTo(String value) {
            addCriterion("value <>", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThan(String value) {
            addCriterion("value >", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueGreaterThanOrEqualTo(String value) {
            addCriterion("value >=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThan(String value) {
            addCriterion("value <", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLessThanOrEqualTo(String value) {
            addCriterion("value <=", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueLike(String value) {
            addCriterion("value like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotLike(String value) {
            addCriterion("value not like", value, "value");
            return (Criteria) this;
        }

        public Criteria andValueIn(List<String> values) {
            addCriterion("value in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotIn(List<String> values) {
            addCriterion("value not in", values, "value");
            return (Criteria) this;
        }

        public Criteria andValueBetween(String value1, String value2) {
            addCriterion("value between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andValueNotBetween(String value1, String value2) {
            addCriterion("value not between", value1, value2, "value");
            return (Criteria) this;
        }

        public Criteria andClientFormIdIsNull() {
            addCriterion("clientformid is null");
            return (Criteria) this;
        }

        public Criteria andClientFormIdIsNotNull() {
            addCriterion("clientformid is not null");
            return (Criteria) this;
        }

        public Criteria andClientFormIdEqualTo(Integer value) {
            addCriterion("clientformid =", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdNotEqualTo(Integer value) {
            addCriterion("clientformid <>", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdGreaterThan(Integer value) {
            addCriterion("clientformid >", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clientformid >=", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdLessThan(Integer value) {
            addCriterion("clientformid <", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdLessThanOrEqualTo(Integer value) {
            addCriterion("clientformid <=", value, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdIn(List<Integer> values) {
            addCriterion("clientformid in", values, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdNotIn(List<Integer> values) {
            addCriterion("clientformid not in", values, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdBetween(Integer value1, Integer value2) {
            addCriterion("clientformid between", value1, value2, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andClientFormIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clientformid not between", value1, value2, "clientFormId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("questionid is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("questionid is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("questionid =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("questionid <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("questionid >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionid >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("questionid <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("questionid <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("questionid in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("questionid not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("questionid between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("questionid not between", value1, value2, "questionId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated do_not_delete_during_merge Thu May 23 14:05:46 PKT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.formquestionclient
     *
     * @mbggenerated Thu May 23 14:05:46 PKT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}