package net.calba.backpain.model;

public class HeightUnits {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heightunits.heightunitsid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer heightUnitsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column heightunits.unitname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String unitName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heightunits.heightunitsid
     *
     * @return the value of heightunits.heightunitsid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getHeightUnitsId() {
        return heightUnitsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heightunits.heightunitsid
     *
     * @param heightUnitsId the value for heightunits.heightunitsid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setHeightUnitsId(Integer heightUnitsId) {
        this.heightUnitsId = heightUnitsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column heightunits.unitname
     *
     * @return the value of heightunits.unitname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column heightunits.unitname
     *
     * @param unitName the value for heightunits.unitname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }
}