package net.calba.backpain.model;

import java.util.ArrayList;
import java.util.List;

public class PersonalDetailsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public PersonalDetailsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPersonalDetailsIdIsNull() {
            addCriterion("personaldetailsid is null");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdIsNotNull() {
            addCriterion("personaldetailsid is not null");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdEqualTo(Integer value) {
            addCriterion("personaldetailsid =", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdNotEqualTo(Integer value) {
            addCriterion("personaldetailsid <>", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdGreaterThan(Integer value) {
            addCriterion("personaldetailsid >", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("personaldetailsid >=", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdLessThan(Integer value) {
            addCriterion("personaldetailsid <", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdLessThanOrEqualTo(Integer value) {
            addCriterion("personaldetailsid <=", value, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdIn(List<Integer> values) {
            addCriterion("personaldetailsid in", values, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdNotIn(List<Integer> values) {
            addCriterion("personaldetailsid not in", values, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdBetween(Integer value1, Integer value2) {
            addCriterion("personaldetailsid between", value1, value2, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andPersonalDetailsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("personaldetailsid not between", value1, value2, "personalDetailsId");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(String value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(String value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(String value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(String value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(String value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(String value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLike(String value) {
            addCriterion("weight like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotLike(String value) {
            addCriterion("weight not like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<String> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<String> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(String value1, String value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(String value1, String value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNull() {
            addCriterion("clinetid is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("clinetid is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("clinetid =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("clinetid <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("clinetid >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("clinetid >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("clinetid <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("clinetid <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("clinetid in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("clinetid not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("clinetid between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("clinetid not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdIsNull() {
            addCriterion("heightunitsid is null");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdIsNotNull() {
            addCriterion("heightunitsid is not null");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdEqualTo(Integer value) {
            addCriterion("heightunitsid =", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdNotEqualTo(Integer value) {
            addCriterion("heightunitsid <>", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdGreaterThan(Integer value) {
            addCriterion("heightunitsid >", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("heightunitsid >=", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdLessThan(Integer value) {
            addCriterion("heightunitsid <", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdLessThanOrEqualTo(Integer value) {
            addCriterion("heightunitsid <=", value, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdIn(List<Integer> values) {
            addCriterion("heightunitsid in", values, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdNotIn(List<Integer> values) {
            addCriterion("heightunitsid not in", values, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdBetween(Integer value1, Integer value2) {
            addCriterion("heightunitsid between", value1, value2, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andHeightUnitsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("heightunitsid not between", value1, value2, "heightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdIsNull() {
            addCriterion("weightunitsid is null");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdIsNotNull() {
            addCriterion("weightunitsid is not null");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdEqualTo(Integer value) {
            addCriterion("weightunitsid =", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdNotEqualTo(Integer value) {
            addCriterion("weightunitsid <>", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdGreaterThan(Integer value) {
            addCriterion("weightunitsid >", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("weightunitsid >=", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdLessThan(Integer value) {
            addCriterion("weightunitsid <", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdLessThanOrEqualTo(Integer value) {
            addCriterion("weightunitsid <=", value, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdIn(List<Integer> values) {
            addCriterion("weightunitsid in", values, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdNotIn(List<Integer> values) {
            addCriterion("weightunitsid not in", values, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdBetween(Integer value1, Integer value2) {
            addCriterion("weightunitsid between", value1, value2, "weightUnitsId");
            return (Criteria) this;
        }

        public Criteria andWeightUnitsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("weightunitsid not between", value1, value2, "weightUnitsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personaldetails
     *
     * @mbggenerated do_not_delete_during_merge Wed May 22 17:15:02 PKT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table personaldetails
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}