package net.calba.backpain.model;

import java.net.URLEncoder;
import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectdesc
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String projectDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectstartdate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Date projectStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectenddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Date projectEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.monitortriggerinterval
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer monitorTriggerInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectid
     *
     * @return the value of project.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectid
     *
     * @param projectId the value for project.projectid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectname
     *
     * @return the value of project.projectname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectname
     *
     * @param projectName the value for project.projectname
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectdesc
     *
     * @return the value of project.projectdesc
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getProjectDesc() {
        return projectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectdesc
     *
     * @param projectDesc the value for project.projectdesc
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc == null ? null : projectDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectstartdate
     *
     * @return the value of project.projectstartdate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Date getProjectStartDate() {
        return projectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectstartdate
     *
     * @param projectStartDate the value for project.projectstartdate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectStartDate(Date projectStartDate) {
        this.projectStartDate = projectStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectenddate
     *
     * @return the value of project.projectenddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Date getProjectEndDate() {
        return projectEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectenddate
     *
     * @param projectEndDate the value for project.projectenddate
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setProjectEndDate(Date projectEndDate) {
        this.projectEndDate = projectEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.monitortriggerinterval
     *
     * @return the value of project.monitortriggerinterval
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getMonitorTriggerInterval() {
        return monitorTriggerInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.monitortriggerinterval
     *
     * @param monitorTriggerInterval the value for project.monitortriggerinterval
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setMonitorTriggerInterval(Integer monitorTriggerInterval) {
        this.monitorTriggerInterval = monitorTriggerInterval;
    }
    
    public String getUrlEncodedtName() {
    	try {
    		 return URLEncoder.encode(projectName, "UTF-8");
    	} catch(Exception e) {
    		return projectName;
    	}
       
    }
}