package net.calba.backpain.model;

public class Question {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.questionid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer questionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.formid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.questiontext
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private String questionText;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.answertype
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private String answerType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.parententityid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer parentEntityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.min_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer minScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.max_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer maxScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.question.questiongroupid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    private Integer questionGroupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.questionid
     *
     * @return the value of calba.question.questionid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.questionid
     *
     * @param questionId the value for calba.question.questionid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.formid
     *
     * @return the value of calba.question.formid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.formid
     *
     * @param formId the value for calba.question.formid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.questiontext
     *
     * @return the value of calba.question.questiontext
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.questiontext
     *
     * @param questionText the value for calba.question.questiontext
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setQuestionText(String questionText) {
        this.questionText = questionText == null ? null : questionText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.answertype
     *
     * @return the value of calba.question.answertype
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public String getAnswerType() {
        return answerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.answertype
     *
     * @param answerType the value for calba.question.answertype
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setAnswerType(String answerType) {
        this.answerType = answerType == null ? null : answerType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.parententityid
     *
     * @return the value of calba.question.parententityid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getParentEntityId() {
        return parentEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.parententityid
     *
     * @param parentEntityId the value for calba.question.parententityid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setParentEntityId(Integer parentEntityId) {
        this.parentEntityId = parentEntityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.min_score
     *
     * @return the value of calba.question.min_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getMinScore() {
        return minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.min_score
     *
     * @param minScore the value for calba.question.min_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.max_score
     *
     * @return the value of calba.question.max_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.max_score
     *
     * @param maxScore the value for calba.question.max_score
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.question.questiongroupid
     *
     * @return the value of calba.question.questiongroupid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public Integer getQuestionGroupId() {
        return questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.question.questiongroupid
     *
     * @param questionGroupId the value for calba.question.questiongroupid
     *
     * @mbggenerated Mon Nov 04 19:28:27 PKT 2013
     */
    public void setQuestionGroupId(Integer questionGroupId) {
        this.questionGroupId = questionGroupId;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Question [questionId=" + questionId + ", formId=" + formId
				+ ", questionText=" + questionText + ", answerType="
				+ answerType + ", parentEntityId=" + parentEntityId
				+ ", minScore=" + minScore + ", maxScore=" + maxScore
				+ ", questionGroupId=" + questionGroupId + "]";
	}
    
    
}