package net.calba.backpain.model;

import java.util.List;

public class QuestionGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.questiongroupid
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer questionGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.formula
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private String formula;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer minScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questiongroup.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer maxScore;
    
    
    private List<Question> questions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.questiongroupid
     *
     * @return the value of calba.questiongroup.questiongroupid
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getQuestionGroupId() {
        return questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.questiongroupid
     *
     * @param questionGroupId the value for calba.questiongroup.questiongroupid
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setQuestionGroupId(Integer questionGroupId) {
        this.questionGroupId = questionGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.description
     *
     * @return the value of calba.questiongroup.description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.description
     *
     * @param description the value for calba.questiongroup.description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.formula
     *
     * @return the value of calba.questiongroup.formula
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public String getFormula() {
        return formula;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.formula
     *
     * @param formula the value for calba.questiongroup.formula
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setFormula(String formula) {
        this.formula = formula == null ? null : formula.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.report_id
     *
     * @return the value of calba.questiongroup.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.report_id
     *
     * @param reportId the value for calba.questiongroup.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setReportId(Integer reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.min_score
     *
     * @return the value of calba.questiongroup.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getMinScore() {
        return minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.min_score
     *
     * @param minScore the value for calba.questiongroup.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questiongroup.max_score
     *
     * @return the value of calba.questiongroup.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questiongroup.max_score
     *
     * @param maxScore the value for calba.questiongroup.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }

	/**
	 * @return the questions
	 */
	public final List<Question> getQuestions() {
		return questions;
	}

	/**
	 * @param questions the questions to set
	 */
	public final void setQuestions(List<Question> questions) {
		this.questions = questions;
	}
    
    
    
}