package net.calba.backpain.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionAnswerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public QuestionAnswerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("questionid is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("questionid is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Integer value) {
            addCriterion("questionid =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Integer value) {
            addCriterion("questionid <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Integer value) {
            addCriterion("questionid >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionid >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Integer value) {
            addCriterion("questionid <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Integer value) {
            addCriterion("questionid <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Integer> values) {
            addCriterion("questionid in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Integer> values) {
            addCriterion("questionid not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Integer value1, Integer value2) {
            addCriterion("questionid between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("questionid not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdIsNull() {
            addCriterion("questionoptionid is null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdIsNotNull() {
            addCriterion("questionoptionid is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdEqualTo(String value) {
            addCriterion("questionoptionid =", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdNotEqualTo(String value) {
            addCriterion("questionoptionid <>", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdGreaterThan(String value) {
            addCriterion("questionoptionid >", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdGreaterThanOrEqualTo(String value) {
            addCriterion("questionoptionid >=", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdLessThan(String value) {
            addCriterion("questionoptionid <", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdLessThanOrEqualTo(String value) {
            addCriterion("questionoptionid <=", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdLike(String value) {
            addCriterion("questionoptionid like", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdNotLike(String value) {
            addCriterion("questionoptionid not like", value, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdIn(List<String> values) {
            addCriterion("questionoptionid in", values, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdNotIn(List<String> values) {
            addCriterion("questionoptionid not in", values, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdBetween(String value1, String value2) {
            addCriterion("questionoptionid between", value1, value2, "questionoptionid");
            return (Criteria) this;
        }

        public Criteria andQuestionOptionIdNotBetween(String value1, String value2) {
            addCriterion("questionoptionid not between", value1, value2, "questionoptionid");
            return (Criteria) this;
        }
        
        //
        public Criteria andAnswerTextIsNull() {
            addCriterion("answertext is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIsNotNull() {
            addCriterion("answertext is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTextEqualTo(String value) {
            addCriterion("answertext =", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotEqualTo(String value) {
            addCriterion("answertext <>", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThan(String value) {
            addCriterion("answertext >", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextGreaterThanOrEqualTo(String value) {
            addCriterion("answertext >=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThan(String value) {
            addCriterion("answertext <", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLessThanOrEqualTo(String value) {
            addCriterion("answertext <=", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextLike(String value) {
            addCriterion("answertext like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotLike(String value) {
            addCriterion("answertext not like", value, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextIn(List<String> values) {
            addCriterion("answertext in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotIn(List<String> values) {
            addCriterion("answertext not in", values, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextBetween(String value1, String value2) {
            addCriterion("answertext between", value1, value2, "answerText");
            return (Criteria) this;
        }

        public Criteria andAnswerTextNotBetween(String value1, String value2) {
            addCriterion("answertext not between", value1, value2, "answerText");
            return (Criteria) this;
        }
        //

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }
        
        //below
        public Criteria andUserIdIsNotNull() {
            addCriterion("userid is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userid =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userid <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userid >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userid >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userid <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userid <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userid in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userid not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userid between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userid not between", value1, value2, "userid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.questionanswer
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 11 20:00:21 PKT 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table calba.questionanswer
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}