package net.calba.backpain.model;

public class QuestionAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questionanswer.questionid
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    private Integer questionId;
    
    private Integer userId;
    

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questionanswer.answertext
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    private String answerText;
    
    private String questionOptionId;
    
    private String dateVal;


	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.questionanswer.score
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questionanswer.questionid
     *
     * @return the value of calba.questionanswer.questionid
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public Integer getQuestionId() {
        return questionId;
    }

    public Integer getUserId() {
        return userId;
    }

    
    public String getDateVal() {
		return dateVal;
	}

	public void setDateVal(String dateVal) {
		this.dateVal = dateVal;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questionanswer.questionid
     *
     * @param questionId the value for calba.questionanswer.questionid
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questionanswer.answertext
     *
     * @return the value of calba.questionanswer.answertext
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public String getAnswerText() {
        return answerText;
    }
    
    

    public String getQuestionOptionId() {
		return questionOptionId;
	}

	public void setQuestionOptionId(String questionOptionId) {
		this.questionOptionId = questionOptionId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questionanswer.answertext
     *
     * @param answerText the value for calba.questionanswer.answertext
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void setAnswerText(String answerText) {
        this.answerText = answerText == null ? null : answerText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.questionanswer.score
     *
     * @return the value of calba.questionanswer.score
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.questionanswer.score
     *
     * @param score the value for calba.questionanswer.score
     *
     * @mbggenerated Mon Nov 11 20:00:21 PKT 2013
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}