package net.calba.backpain.model;

import java.util.List;

public class Report {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.report.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Long reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.report.report_name
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.report.report_description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.report.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer minScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column calba.report.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    private Integer maxScore;
    
    
    private List<QuestionGroup> questionGroups;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.report.report_id
     *
     * @return the value of calba.report.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Long getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.report.report_id
     *
     * @param reportId the value for calba.report.report_id
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.report.report_name
     *
     * @return the value of calba.report.report_name
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.report.report_name
     *
     * @param name the value for calba.report.report_name
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.report.report_description
     *
     * @return the value of calba.report.report_description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.report.report_description
     *
     * @param description the value for calba.report.report_description
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.report.min_score
     *
     * @return the value of calba.report.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getMinScore() {
        return minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.report.min_score
     *
     * @param minScore the value for calba.report.min_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setMinScore(Integer minScore) {
        this.minScore = minScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column calba.report.max_score
     *
     * @return the value of calba.report.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column calba.report.max_score
     *
     * @param maxScore the value for calba.report.max_score
     *
     * @mbggenerated Sat Dec 07 17:12:42 PKT 2013
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }
    
	/**
	 * @return the questionGroups
	 */
	public final List<QuestionGroup> getQuestionGroups() {
		return questionGroups;
	}

	/**
	 * @param questionGroups the questionGroups to set
	 */
	public final void setQuestionGroups(List<QuestionGroup> questionGroups) {
		this.questionGroups = questionGroups;
	}
    
    
}