package net.calba.backpain.model;

public class Telephone {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telephone.telephone_id
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer telephoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telephone.phone_number
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private String phoneNumber;
    private String mobileNumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column telephone.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    private Integer clientId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telephone.telephone_id
     *
     * @return the value of telephone.telephone_id
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getTelephoneId() {
        return telephoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telephone.telephone_id
     *
     * @param telephoneId the value for telephone.telephone_id
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setTelephoneId(Integer telephoneId) {
        this.telephoneId = telephoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telephone.phone_number
     *
     * @return the value of telephone.phone_number
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telephone.phone_number
     *
     * @param phoneNumber the value for telephone.phone_number
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column telephone.clinetid
     *
     * @return the value of telephone.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column telephone.clinetid
     *
     * @param clientId the value for telephone.clinetid
     *
     * @mbggenerated Wed May 22 17:15:02 PKT 2013
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

	public String getMobileNumber() {
		return mobileNumber;
	}

	public void setMobileNumber(String mobileNumber) {
		 this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
	}
}